# question 8

In [23]:
import warnings
import numpy as np

In [58]:
p = np.array([2,3,1,0,6,7])
p

array([2, 3, 1, 0, 6, 7])

In [59]:
for index,item in enumerate(p):
     if item!=0:
         print(item, 'is Non-zero value')
     else: 
        print(item, "is zero value")
        

2 is Non-zero value
3 is Non-zero value
1 is Non-zero value
0 is zero value
6 is Non-zero value
7 is Non-zero value


# question 9

In [55]:
a = np.array([1, 0, np.nan, np.NINF, -2, np.inf])
a

array([  1.,   0.,  nan, -inf,  -2.,  inf])

In [56]:
print("Testing array x element-wise for finiteness:")
print(np.isfinite(a))

Testing array x element-wise for finiteness:
[ True  True False False  True False]


In [54]:
m = np.array([1, 0, np.nan, np.NINF, -2, np.inf])
m
print("Testing array x element-wise for positive or negative infinity:")
print(np.isinf(m))

Testing array x element-wise for positive or negative infinity:
[False False False  True False  True]


# question 10

In [53]:
z = np.array([1, 4.5, 0, 1j, np.nan, np.NINF, -2, np.inf])
z
print("Testing element-wise for not a number(NaN):")
print(np.isnan(z))

Testing element-wise for not a number(NaN):
[False False False False  True False False False]


In [74]:
x= np.array([3+2j, 1+0j, 4.5, 0, 3, 2, 2j, 100, 26.5j])
x

array([  3.  +2.j ,   1.  +0.j ,   4.5 +0.j ,   0.  +0.j ,   3.  +0.j ,
         2.  +0.j ,   0.  +2.j , 100.  +0.j ,   0. +26.5j])

In [70]:
print("Testing for complex numbers in array:")
print(np.iscomplex(x))

Testing for complex numbers in array:
[ True False False False False False  True False  True]


In [71]:
print("Testing for real numbers in array:")
print(np.isreal(x))

Testing for real numbers in array:
[False  True  True  True  True  True False  True False]


In [72]:
print("Testing for scalar in array:")
for index,item in enumerate(x):
    print(isinstance(item, np.generic))

Testing for scalar in array:
True
True
True
True
True
True
True
True
True


# question 11

In [81]:
element1 = np.array([[1,2,3], [20,30,40], [4,5,6]] )
element2 = np.array([[0,1,2], [10,15,20], [11,12,13]])
print(element1)
print(" \n ")
print(element2)

[[ 1  2  3]
 [20 30 40]
 [ 4  5  6]]
 
 
[[ 0  1  2]
 [10 15 20]
 [11 12 13]]


In [82]:
np.array_equal(element1,element2)

False

In [83]:
np.array_equiv(element1,element2)

False

In [84]:
np.allclose(element1,element2)

False

In [97]:
lilian = np.array([10, -2, -30, 40, 50, 60, 70, -80])
owino = np.array([20, -5, -10, 10, 50, 60, 10, -60])
print(lilian)
print(" \n ")
print(owino)

[ 10  -2 -30  40  50  60  70 -80]
 
 
[ 20  -5 -10  10  50  60  10 -60]


In [98]:
print("Array lilian: ", lilian)
print("Array owino: ", owino)
print("lilian > owino")
print(np.greater(lilian, owino))

Array lilian:  [ 10  -2 -30  40  50  60  70 -80]
Array owino:  [ 20  -5 -10  10  50  60  10 -60]
lilian > owino
[False  True False  True False False  True False]


In [100]:
print("lilian >= owino")
print(np.greater_equal(lilian, owino))

lilian >= owino
[False  True False  True  True  True  True False]


In [101]:
print("lilian < owino")
print(np.less(lilian, owino))

lilian < owino
[ True False  True False False False False  True]


In [102]:
print("lilian <= owino")
print(np.less_equal(lilian,owino))

lilian <= owino
[ True False  True False  True  True False  True]


In [103]:
print('lilian %= owino')
print(np.not_equal(lilian, owino))

lilian %= owino
[ True  True  True  True False False  True  True]


# question 12

In [110]:
p = np.array([[3,7,5], [8,4,3], [2,4,9]])
q = np.array([[3,7,5], [8,4,3], [2,4,9]])
np.array_equal(p, q)

True

In [111]:
np.allclose(p, q)

True

In [112]:
np.array_equiv(p, q)

True

In [117]:
tech = np.array([1, 7, 13, 105])
tech

array([  1,   7,  13, 105])

In [118]:
print("%d bytes" %(tech.size * tech.itemsize))

16 bytes
